using Microsoft.Exchange.Data.Mime;
using Microsoft.Exchange.Data.Transport;
using Microsoft.Exchange.Data.Transport.Email;
using Microsoft.Exchange.Data.Transport.Routing;
using System;
using System.Diagnostics;
using System.Linq;
using System.Net.Mail;
using System.Text;



namespace TransportAgents
{
    public class AutoResponderAgent : RoutingAgentFactory
    {

        public override RoutingAgent CreateAgent(SmtpServer server)
        {
            return new AutoResponderAgent_Agent(server);
        }
    }

    public class AutoResponderAgent_Agent : RoutingAgent
    {

        static string LogFile = String.Format("F:\\Transport Agents\\{0}.log", "AutoResponderAgent");
        TextLogger TextLog = new TextLogger(LogFile);

        public AutoResponderAgent_Agent(SmtpServer server)
        {
            this.OnRoutedMessage += OnRoutedMessageGenerateAutoResponse;
        }

        private void OnRoutedMessageGenerateAutoResponse(RoutedMessageEventSource source, QueuedMessageEventArgs e)
        {
            TextLog.WriteToText("Entering: OnRoutedMessageGenerateAutoResponse");

            try
            {
                string sender = e.MailItem.FromAddress.ToString();
                string autoResponseSubject = "This email address will be deprecated";
                string autoResponseBody = "Thank you for your e-mail; this email address will be deprecated and won't receive messages anymore.";
                string headerName = "X-TOTONI-AUTORESPONSE";
                string headerValue = "This autoresponse message has been generated by a Transpor Agent written by TOTONI@MICROSOFT.COM";
                MailMessage autoResponse = new MailMessage();

                autoResponse.From = new MailAddress("NoReply@TONIOLO.CLOUD");
                autoResponse.Sender = new MailAddress("NoReply@TONIOLO.CLOUD");
                autoResponse.To.Add(new MailAddress(sender));
                autoResponse.Subject = autoResponseSubject;
                autoResponse.Body = autoResponseBody;
                autoResponse.IsBodyHtml = false;
                autoResponse.Headers.Add(headerName, headerValue);

                // Need to find how to send the "autoResponse" MailMessage here
            }
            catch (Exception ex)
            {
                TextLog.WriteToText("------------------------------------------------------------");
                TextLog.WriteToText("EXCEPTION!!!");
                TextLog.WriteToText("------------------------------------------------------------");
                TextLog.WriteToText(String.Format("HResult: {0}", ex.HResult.ToString()));
                TextLog.WriteToText(String.Format("Message: {0}", ex.Message.ToString()));
                TextLog.WriteToText(String.Format("Source: {0}", ex.Source.ToString()));
            }

            return;

        }
    }

}
