using Microsoft.Exchange.Data.Transport;
using Microsoft.Exchange.Data.Transport.Routing;
using System;
using System.Diagnostics;
using System.Net.Mail;



namespace TransportAgents
{
    public class AutoResponderAgent : RoutingAgentFactory
    {

        public override RoutingAgent CreateAgent(SmtpServer server)
        {
            return new AutoResponderAgent_Agent(server);
        }
    }

    public class AutoResponderAgent_Agent : RoutingAgent
    {

        EventLogger EventLog = new EventLogger("AutoResponderAgent");
        static bool IsDebugEnabled = true;

        public AutoResponderAgent_Agent(SmtpServer server)
        {
            this.OnRoutedMessage += OnRoutedMessageGenerateAutoResponse;
        }

        private void OnRoutedMessageGenerateAutoResponse(RoutedMessageEventSource source, QueuedMessageEventArgs e)
        {
            try
            {
                Stopwatch stopwatch = Stopwatch.StartNew();
                EventLog.AppendLogEntry(String.Format("Entering: AutoResponderAgent:OnRoutedMessageGenerateAutoResponse"));

                string sender = e.MailItem.FromAddress.ToString();
                string autoResponseSubject = "This email address will be deprecated";
                string autoResponseBody = "Thank you for your e-mail; this email address will be deprecated and won't receive messages anymore.";
                string headerName = "X-TOTONI-AUTORESPONSE";
                string headerValue = "This autoresponse message has been generated by a Transpor Agent written by TOTONI@MICROSOFT.COM";
                MailMessage autoResponse = new MailMessage();

                autoResponse.From = new MailAddress("NoReply@TONIOLO.CLOUD");
                autoResponse.Sender = new MailAddress("NoReply@TONIOLO.CLOUD");
                autoResponse.To.Add(new MailAddress(sender));
                autoResponse.Subject = autoResponseSubject;
                autoResponse.Body = autoResponseBody;
                autoResponse.IsBodyHtml = false;
                autoResponse.Headers.Add(headerName, headerValue);

                // Need to find how to send the "autoResponse" MailMessage here

                EventLog.AppendLogEntry(String.Format("AutoResponderAgent:OnRoutedMessageInsertHeader took {0} ms to execute", stopwatch.ElapsedMilliseconds));
                EventLog.LogDebug(IsDebugEnabled);
            }
            catch (Exception ex)
            {
                EventLog.AppendLogEntry("Exception in AutoResponderAgent:OnRoutedMessageGenerateAutoResponse");
                EventLog.AppendLogEntry(ex);
                EventLog.LogError();
            }

            return;

        }
    }

}
