name: TransportAgents .NETFramework Build

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest
    env:
      Solution_Name: TransportAgents.sln
    steps:

    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2
    
    - name: Build Solution
      run: |
        msbuild.exe $env:Solution_Name /p:platform="Any CPU" /p:configuration="Release"
